[package]
name = "czkawka_core"
version = "1.1.0"
authors = ["Rafał Mikrut <mikrutrafal@protonmail.com>"]
edition = "2018"
description = "Core of Czkawka app"
license = "MIT"
homepage = "https://github.com/qarmin/czkawka"
repository = "https://github.com/qarmin/czkawka"


[dependencies]
humansize = "1"
blake3 = "0.3"
#rayon = "1"
crossbeam-channel = "0.4.4"
img_hash = "3.1.0"
bk-tree = "0.3.0"